stages:
  - go-build
  - docker

go-build:
  only:
    - main
  stage: go-build
  image: golang # 利用Golang容器进行打包Golang项目
  script:
    - go env -w GOPROXY=https://goproxy.cn,direct
    - go env -w GOPRIVATE='gitlab.hknet-inc.com'
    - go get
    - GOOS=linux GOARCH=amd64 go build -o temp/linux_amd64/main main.go
    - chmod +x temp/linux_amd64/main

docker-build:
  only:
    - main
  image: maven:3.6.3-jdk-8-slim
  stage: docker
  script:
    - echo 'hello docker build'
