stages:
  - daily_build
  - daily_deploy
  - daily_push

variables:
  IMAGE_GROUP: xxx
  NAME_SPACE: xxx
  GOPATH: ${CI_PROJECT_DIR}/.go
  GOMODCACHE: ${CI_PROJECT_DIR}/.go/pkg/mod
  GOCACHE: ${CI_PROJECT_DIR}/.go/.cache/go-build
  GOLANGCI_LINT_CACHE: ${CI_PROJECT_DIR}/.go/.cache/golangci-lint

daily_build:
  only:
    - main
  image: docker
  stage: daily_build
  script:
    - rm -rf version.txt && echo "daily,buildtime:"$(date +%Y%m%d%H%M)"" > version.txt
    - docker build -f manifest/docker/Dockerfile -t easzlab.io.local:5000/unibee/unibee-api:daily --platform linux/amd64 .
    - docker push easzlab.io.local:5000/unibee/unibee-api:daily

daily_deploy:
  only:
    - main
  image: registry.cn-shenzhen.aliyuncs.com/heiku/kubectl:latest
  stage: daily_deploy
  script:
    - kubectl --kubeconfig /data/kubeconfigs/unib_dev_configs rollout restart deployment/unibee-api-daily


daily_push:
  only:
    - main
  image: docker
  stage: daily_push
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker tag easzlab.io.local:5000/unibee/unibee-api:daily unibee/api:stage
    - docker push unibee/api:stage

tag:
  only:
    - tags
  image: docker
  stage: tag
  script:
    - rm -rf version.txt && echo "$CI_COMMIT_TAG-premium,buildtime:"$(date +%Y%m%d%H%M)"" > version.txt
    - docker build -f manifest/docker/Dockerfile -t unibee/api:$CI_COMMIT_TAG-premium --platform linux/amd64 .
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker push unibee/api:${CI_COMMIT_TAG}-premium
