stages:
  - build
  - deploy

variables:
  IMAGE_GROUP: xxx
  NAME_SPACE: xxx
  GOPATH: ${CI_PROJECT_DIR}/.go
  GOMODCACHE: ${CI_PROJECT_DIR}/.go/pkg/mod
  GOCACHE: ${CI_PROJECT_DIR}/.go/.cache/go-build
  GOLANGCI_LINT_CACHE: ${CI_PROJECT_DIR}/.go/.cache/golangci-lint

build:
  only:
    - main
#  tags:
#    - unib
  stage: build
  image: golang # 利用Golang容器进行打包Golang项目
  script:
    - ls -al /data/
    - go env -w GOPROXY=https://goproxy.cn,direct
    - go env -w GOPRIVATE='gitlab.hknet-inc.com'
    - go get
    - GOOS=linux GOARCH=amd64 go build -o temp/linux_amd64/main main.go
    - chmod +x temp/linux_amd64/main
    - cp temp/linux_amd64/main /data/artifacts/main

deploy:
  only:
    - main
#  tags:
#    - unib
  image: docker
  stage: deploy
  script:
    - mkdir -p temp/linux_amd64
    - cp /data/artifacts/main temp/linux_amd64/main
    - docker build -f manifest/docker/Dockerfile -t registry.cn-shenzhen.aliyuncs.com/heiku/heiku_gooverseapay:daily .
    - docker login --username=黑酷网络技术 --password=123456abc registry.cn-shenzhen.aliyuncs.com
    - docker push registry.cn-shenzhen.aliyuncs.com/heiku/heiku_gooverseapay:daily

