stages:
  - build
  - push
  - deploy

variables:
  IMAGE_GROUP: xxx
  NAME_SPACE: xxx
  GOPATH: ${CI_PROJECT_DIR}/.go
  GOMODCACHE: ${CI_PROJECT_DIR}/.go/pkg/mod
  GOCACHE: ${CI_PROJECT_DIR}/.go/.cache/go-build
  GOLANGCI_LINT_CACHE: ${CI_PROJECT_DIR}/.go/.cache/golangci-lint

build:
  only:
    - mains
  stage: build
  image: golang # 利用Golang容器进行打包Golang项目
  script:
    - ls -al /data/
    - go env -w GOPROXY=https://goproxy.cn,direct
    - go env -w GOPRIVATE='gitlab.hknet-inc.com'
    - go get
    - GOOS=linux GOARCH=amd64 go build -o temp/linux_amd64/main main.go
    - chmod +x temp/linux_amd64/main
    - cp temp/linux_amd64/main /data/artifacts/main

push:
  only:
    - main
  image: docker
  stage: push
  script:
    - mkdir -p temp/linux_amd64
    - cp /data/artifacts/main temp/linux_amd64/main
    - chmod +x /temp/linux_amd64/main
    - docker rmi registry.cn-shenzhen.aliyuncs.com/heiku/heiku_gooverseapay:daily
    - docker build -f manifest/docker/Dockerfile -t registry.cn-shenzhen.aliyuncs.com/heiku/heiku_gooverseapay:daily --platform linux/amd64 .
    - docker login --username=${ALIYUN_ACCOUNT} --password=${ALIYUN_PASSWORD} registry.cn-shenzhen.aliyuncs.com
    - docker push registry.cn-shenzhen.aliyuncs.com/heiku/heiku_gooverseapay:daily

deploy:
  only:
    - mains
  image: registry.cn-shenzhen.aliyuncs.com/heiku/kubectl:latest
  stage: deploy
  script:
    - kubectl --kubeconfig /data/kubeconfigs/unib_dev_configs rollout restart deployment/yd-unib-server-daily
    - kubectl --kubeconfig /data/kubeconfigs/unib_dev_configs rollout status deployment/yd-unib-server-daily
#    - kubectl --kubeconfig /data/kubeconfigs/frps_local_configs rollout restart deployment/yd-gooverseapay-daily