# This template uses jdk8 for verifying and deploying images
image: maven:3.6.3-jdk-8-slim

stages:
  - package
  - docker

package-build:
  only:
    - master
  stage: package
  script:
    - echo 'hello package build'

docker-build:
  only:
    - master
  stage: docker
  script:
    - echo 'hello docker build'