env: hklocal
host_path: https://daily.hknet-inc.com/overseapay

server:
  address:     ":8080"
  openapiPath: "/api.json"
#  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true



database:
  xin:
    link:    "mysql:root:YW1lc3BhY2UiOiJrdWJlcm5ld@tcp(frps.hknet-inc.com:7111)/xin"
    debug:   true
    type:    mysql
  oversea_pay:
    link:    "mysql:root:YW1lc3BhY2UiOiJrdWJlcm5ld@tcp(frps.hknet-inc.com:7111)/oversea_pay"
    debug:   true
    type:    mysql    

# Redis 配置示例
redis:
  # 单实例配置示例1
  default:
    address: frps.hknet-inc.com:7112
    db:      0
    pass: p9KIMXc8OXI5HnaA
    maxIdle: 500
    minIdle: 10
    idleTimeout: 1d    

  # # 单实例配置示例2
  # cache:
  #   address:     127.0.0.1:6379
  #   db:          1
  #   pass:        123456
  #   idleTimeout: 600