
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    name:     "main"
    arch:     "amd64"
    system:   "linux,darwin"
    mod:      "none"
    packSrc:  "resource,manifest"
    version:  "v1.0.0"
    output:   "./bin"
    extra:    ""
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
  gen:
    dao:
      - link:     "mysql:root:***REMOVED***@tcp(frps.hknet-inc.com:7111)/xin"
        tables:   "test"
        group: "xin"
        daoPath:  "dao/xin"
        doPath:  "model/do/xin"
        entityPath:  "model/entity/xin"
#        jsonCase: "CamelLower"

      - link:   "mysql:root:***REMOVED***@tcp(frps.hknet-inc.com:7111)/gooversea_pay"
#        path:   "oversea_pay"
#        prefix: "primary_"
        group: "oversea_pay"
        daoPath:  "dao/oversea_pay"
        doPath:  "model/do/oversea_pay"
        entityPath:  "model/entity/oversea_pay"
        tables: ""
#
#      - link:   "mysql:root:***REMOVED***@tcp(frps.hknet-inc.com:7111)/auth"
#        group: "auth"
#        daoPath:  "dao/auth"
#        doPath:  "model/do/auth"
#        entityPath:  "model/entity/auth"
#        tables: "user_account"
#
#      - link:   "mysql:root:***REMOVED***@tcp(frps.hknet-inc.com:7111)/company"
#        group: "company"
#        daoPath:  "dao/company"
#        doPath:  "model/do/company"
#        entityPath:  "model/entity/company"
#        tables: "company_info"