
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    name:     "main"
    arch:     "amd64"
    system:   "linux,darwin"
    mod:      "none"
    packSrc:  "resource,manifest"
#    version:  "auth.0.0"
    output:   "./bin"
    extra:    ""
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - registry.cn-shenzhen.aliyuncs.com/heiku
  gen:
    dao:
      - link:   "mysql:unib:hn02le34lkdLKD@tcp(***REMOVED***:13306)/unib?loc=Local&parseTime=true"
        group: "default"
        daoPath:  "dao/oversea_pay"
        doPath:  "model/do/oversea_pay"
        entityPath:  "model/entity/oversea_pay"
        noModelComment: false
        descriptionTag: true
        tables: ""