#deploy
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yd-gooverseapay-daily
  namespace: default
spec:
  selector:
    matchLabels:
      app: yd-gooverseapay-daily
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: yd-gooverseapay-daily
    spec:
      restartPolicy: Always
      securityContext: {}
      imagePullSecrets:
        - name: heikualy
      containers:
        - name: yd-gooverseapay-daily
          image: registry.cn-shenzhen.aliyuncs.com/heiku/heiku_gooverseapay:daily
          imagePullPolicy: Always
          env:
            - name: MODE
              value: "go"
            - name: dubbo.consumer.check
              value: "false"
            - name: nacos.port
              value: "8848"
            - name: nacos.namespace
              value: "hklocal"
            - name: nacos.group
              value: "config"
            - name: nacos.data.id
              value: "hk-go-settings.yaml"
            - name: nacos.ip
              value: "heiku-nacos-daily-svc"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9999
              name: debug
            - containerPort: 8808
              name: dubbo
            - containerPort: 8848
              name: dubbo-nacos
#          livenessProbe:         #pod内容器健康检查的设置，详情请见http://blog.csdn.net/liyingke112/article/details/77531584
#            httpGet:             #通过httpget检查健康，返回200-399之间，则认为容器正常
#              path: /overseapay/status/env             #URI地址
#              port: 8080
#              scheme: HTTP
#            initialDelaySeconds: 30 #表明第一次检测在容器启动后多长时间后开始
#            periodSeconds: 10    #检查间隔时间
#            timeoutSeconds: 10    #检测的超时时间
#            failureThreshold: 100
#          readinessProbe:
#            failureThreshold: 600
#            httpGet:
#              path: /overseapay/status/env
#              port: 8080
#              scheme: HTTP
#            initialDelaySeconds: 10
#            periodSeconds: 5
#            successThreshold: 5
#            timeoutSeconds: 10

---
#service
apiVersion: v1
kind: Service
metadata:
  name: yd-gooverseapay-daily-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: debug
      port: 9999
      protocol: TCP
      targetPort: debug
  selector:
    app: yd-gooverseapay-daily