#deploy
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yd-unib-server-daily
  namespace: default
spec:
  selector:
    matchLabels:
      app: yd-unib-server-daily
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: yd-unib-server-daily
    spec:
      restartPolicy: Always
      securityContext: {}
      containers:
        - name: yd-unib-server-daily
          image: easzlab.io.local:5000/unibee/unibee-api:daily
          imagePullPolicy: Always
          env:
            - name: MODE
              value: "go"
            - name: dubbo.consumer.check
              value: "false"
            - name: nacos.port
              value: "8848"
            - name: nacos.namespace
              value: "daily"
            - name: nacos.group
              value: "config"
            - name: nacos.data.id
              value: "unib-settings.yaml"
            - name: nacos.ip
              value: "unib-nacos-svc"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9999
              name: debug
            - containerPort: 8808
              name: dubbo
            - containerPort: 8848
              name: dubbo-nacos
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 100
          readinessProbe:
            failureThreshold: 600
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 5
            timeoutSeconds: 10

---
#service
apiVersion: v1
kind: Service
metadata:
  name: yd-unib-server-daily-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: debug
      port: 9999
      protocol: TCP
      targetPort: debug
  selector:
    app: yd-unib-server-daily