name: Release the latest version

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Update version.txt
        run: echo "${{ github.event.client_payload.version }}" > version.txt

      - name: Build prod image and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: manifest/docker/Dockerfile
          push: true
          tags: "unibee/api:${{ github.event.client_payload.version }}"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generateReleaseNotes: true
